/*
 * Copyright (c) 2024, Altomani Gianluca <altomanigianluca@gmail.com>
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <AK/Random.h>
#include <LibCrypto/Curves/Ed448.h>

namespace Crypto::Curves {

// https://datatracker.ietf.org/doc/html/rfc8032#section-5.2.5
ErrorOr<ByteBuffer> Ed448::generate_private_key()
{
    // The private key is 57 octets (456 bits, corresponding to b) of
    // cryptographically secure random data.  See [RFC4086] for a discussion
    // about randomness.

    auto buffer = TRY(ByteBuffer::create_uninitialized(key_size()));
    fill_with_random(buffer);
    return buffer;
}

// https://datatracker.ietf.org/doc/html/rfc8032#section-5.2.5
ErrorOr<ByteBuffer> Ed448::generate_public_key(ReadonlyBytes private_key)
{
    // The 57-byte public key is generated by the following steps:

    return TRY(ByteBuffer::copy(private_key)); // FIXME
}

}
